### PR TITLE
Simplify derivatives

### PR DESCRIPTION
**Pull request by martin-gmx**
Hi Andy.
These changes should allow us to more easily add other forms of derivatives.

II am still trying to get my head around this double derivatives - that we take the derivative of v wrt all parameters, but v already linearizes (i.e., takes the derivative of all parameters). Couldn't we try to use the chain rule and remove this multiplication of derivatives?

Cheers
Martin

### CODE REVIEW

**Comment by mattfidler** [comment]
Hi @andrewhooker and @martin-gmx ;  Does this imply you need to use `deSolve`;  I was working something out with nlmixr that integrates with PopED, but uses RxODE.  I haven't tested it but will abandon it if you require `deSolve`

**Comment by sibojan** [comment]
My personal experience is that RxODE is much easier to use than deSolve. I would vote for PopED+RxODE.

**Comment by andrewhooker** [comment]
Hi

No. We do not require deSolve. Other tools and packages can be used. All of the standard model simulation package for population models can be used as input to poped.

Andy

**Comment by martin-gmx** [comment]
The use provides the model solution - and in the future we will (hopefully) be able to use also the partial derivatives of the solution w.r.t. the model parameters, if the user provides them.

**Comment by mattfidler** [comment]
You can request derivatives from RxODE too, perhaps this couod be helpful
here Martin.

**Comment by andrewhooker** [comment]
Looks good Martin!

**Pull request merged**
